### ISSUE TITLE
BUG: E0904 failed to wake up

### ISSUE THREAD

**Issue by fiveseven-lambda** [naskya/darugarami#2]
Describe the bug: My body randomly fails to wake up early in the morning.

Expected behaviour: It should wake up as soon as the alarm goes off.

How to reproduce: Unknown.

Below is the log:
09/04 01:00 I got sleep.
09/04 07:00 The alarm went off.
09/04 07:30 The alarm went off again.
09/04 08:20 I woke up.

**Comment by naskya** [comment]
This is an expected behavior.
